version: 0.2
env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: ""
        BUILD_FOLDER: "dist"
        BUILD_ENV: "prod"
phases:
 install:
  runtime-Version:
   Nodejs: 14
  commands:
            - echo Installing source NPM dependencies...
            - npm install --legacy-peer-deps
            - npm install -g @angular/cli
build:
  commands:
            - echo Build started
            - ng build 
artifacts:
    files:
        - '**/*'
    base-directory:
    discard-paths: yes
